# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# 1.) Run Unit tests.
- task: DotNetCoreCLI@2
  displayName: 'run unit tests'
  inputs:
    command: test
    projects: '**/*Test*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# 2.) Build the code.
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# 3.) Create artifacts zip package.
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src/SimpleAPI/SimpleAPI.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# 4.) Publish zipped artifacts.
- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'